services:
  mcp-serper:
    build: .
    container_name: mcp-serper-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: [ "python", "serper_mcp.py" ]

  deepresearch-webapp:
    build: .
    container_name: deepresearch-webapp
    depends_on:
      - mcp-serper
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    command: [ "streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0" ]
